version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: crm-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: bun run src/server.ts

  mongo:
    image: mongo:7
    container_name: crm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
